### ISSUE TITLE
Docker command produces error

### ISSUE THREAD

**Issue by griff4692** [nicolov/segmentation_keras#10]
> Traceback (most recent call last):
>   File "./convert.py", line 60, in <module>
>     main()
>   File "./convert.py", line 56, in main
>     args.phase)
>   File "./convert.py", line 32, in convert
>     with open(data_output_path, 'wb') as data_out:
> IOError: [Errno 2] No such file or directory: '../converted/dilation8_pascal_voc.npy'

How do I fix this?  Thanks so much and thanks for the awesome code!

**Comment by griff4692** [comment]
Nevermind.  My mistake...just needed to created conversion dir
